"""
Input preparation for the images that are sent TO the try-on model.

Scope
-----
This module only ever touches the two images the extension uploads: the
user's own profile photo (human_image) and the retailer's product photo
(garment_image). It validates them and, when the container is one the
upstream model cannot decode, rewrites it as a plain PNG before
inference. The image generated by IDM-VTON is never opened, rewritten
or post-processed anywhere in here.

Why this lives in its own module
--------------------------------
backend/main.py is guarded by harness_popup.js, which asserts that the
endpoint file contains no image decoding of its own. The decoder
therefore lives here, and main.py only calls prepare_input_image().

Why normalisation is needed at all
----------------------------------
The upstream Space pins an old Pillow that predates AVIF support, so an
AVIF upload cannot be opened there. Retail CDNs decide the response
format from the request's Accept header, and the answers differ per
site:

    Request Accept header:  */*        image/avif,image/webp,...
    Myntra (myntassets)     image/jpeg image/jpeg      <- always JPEG
    AJIO   (assets.ajio)    image/jpeg image/avif      <- AVIF if offered

A JPEG URL on AJIO can therefore deliver AVIF bytes. Whatever arrives,
it is converted to a format the model can always read.
"""

import os
import tempfile

from PIL import Image


# Formats the upstream model can already decode. Files in these formats
# are passed through byte for byte, so nothing about an existing working
# site can change.
PASSTHROUGH_FORMATS = (
    "PNG",
    "JPEG"
)

# Anything smaller than this cannot be a real product or profile photo.
MINIMUM_BYTES = 64


class ImageNotUsable(Exception):
    """
    Raised when an uploaded image cannot be used for a try-on.
    """


def prepare_input_image(
    path,
    label: str = "image"
):
    """
    Validate an uploaded image and return a path the model can decode.

    Returns the original path unchanged when the file is already a
    plain PNG or JPEG. When it is any other (or unknown) container the
    image is decoded and re-encoded as PNG, and the new path is
    returned. Raises ImageNotUsable when the file is empty, unreadable
    or not a raster image at all - callers must not send such a file to
    the model.
    """

    if not path or not os.path.exists(path):

        raise ImageNotUsable(
            f"{label}: no file was received"
        )

    size = os.path.getsize(path)

    if size < MINIMUM_BYTES:

        raise ImageNotUsable(
            f"{label}: only {size} bytes were received"
        )

    prepared_path = path

    try:

        with Image.open(path) as image:

            # load() forces a real decode, so a truncated or corrupt
            # file is rejected here rather than inside the model.
            image.load()

            image_format = image.format
            width, height = image.size
            mode = image.mode

            print(
                f"[{label}] format={image_format} "
                f"dimensions={width}x{height} mode={mode} "
                f"bytes={size}"
            )

            if width <= 0 or height <= 0:

                raise ImageNotUsable(
                    f"{label}: reported an empty size "
                    f"({width}x{height})"
                )

            if image_format in PASSTHROUGH_FORMATS:

                print(
                    f"[{label}] already {image_format}, "
                    "passing through unchanged"
                )

            else:

                # A container the model may not be able to open
                # (for example AVIF). Re-encode it losslessly.
                prepared_path = _reencode_as_png(
                    image,
                    label,
                    size
                )

    except ImageNotUsable:

        raise

    except Exception as error:

        raise ImageNotUsable(
            f"{label}: not a readable image "
            f"({type(error).__name__})"
        ) from error

    return prepared_path


def _reencode_as_png(
    image,
    label: str,
    original_bytes: int
) -> str:
    """
    Write a decoded image out as a plain RGB PNG and return its path.
    """

    handle = tempfile.NamedTemporaryFile(
        delete=False,
        suffix=".png",
        prefix="tryon_normalised_"
    )

    prepared_path = handle.name
    handle.close()

    frame = image.convert("RGB")

    try:

        frame.save(
            prepared_path,
            format="PNG"
        )

    except Exception:

        _remove(prepared_path)

        raise

    finally:

        frame.close()

    print(
        f"[{label}] normalised to PNG -> {prepared_path} "
        f"({original_bytes} bytes in, "
        f"{os.path.getsize(prepared_path)} bytes out)"
    )

    return prepared_path


def _remove(path) -> None:
    """
    Delete a temporary file, ignoring any failure.
    """

    try:

        if path and os.path.exists(path):

            os.remove(path)

    except Exception:

        pass
